# Generated by Django 3.0.2 on 2020-02-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jboard', '0002_auto_20200225_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsers',
            options={'ordering': ['position']},
        ),
    ]
